/**
 * ข้อมูลตัวอย่าง (Mock Data) สำหรับร้านโรว์เฮ้าส์
 * ใช้เมื่อ NEXT_PUBLIC_DATA_MODE=mock (ค่าเริ่มต้น)
 *
 * อัปเดตตาม Rowhou8e OPS SRS v1.0: 4 แผนก (ครัวขนม/ครัวผลิตขนมปัง/ครัวบาร์น้ำ/ครัวจิปาถะ),
 * ระบบล็อตสินค้า (products/productLots แทน milkBatches เดิม), เช็กลิสต์ 9 สถานะ + ทำย้อนหลังได้
 *
 * หมายเหตุ: ข้อมูลชุดนี้อ้างอิงวันที่ปัจจุบัน (TODAY) แบบ dynamic
 * เพื่อให้เดโมสถานะ "ใกล้หมดอายุ", "หมดอายุ", "ยังไม่ได้ตรวจวันนี้" ได้สมจริงทุกครั้งที่เปิดระบบ
 */
import type {
  AppNotification,
  AppSettings,
  CashReport,
  ChecklistRun,
  ChecklistTemplateItem,
  Employee,
  HistoryLog,
  OrderReminder,
  Product,
  ProductLot,
  PurchaseOrder,
  PurchaseRequest,
  Station,
  StockCategory,
  StockItem,
  StoreHoliday,
  Supplier,
  SupplierItemPrice,
} from './types';

const pad = (n: number) => String(n).padStart(2, '0');
const toDateStr = (d: Date) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
const addDays = (base: Date, days: number) => {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d;
};
const addHours = (base: Date, hours: number) => {
  const d = new Date(base);
  d.setHours(d.getHours() + hours);
  return d;
};

export const NOW = new Date();
export const TODAY_STR = toDateStr(NOW);

// ===================== แผนก (4 แผนกตามสเปก Rowhou8e OPS) =====================
// หมายเหตุ: ในโค้ดยังใช้ชื่อภายในว่า station/stationId (ของเดิม) — หน้าจอแสดงเป็น "แผนก"
export const stations: Station[] = [
  { id: 'stn-dessert', name: 'ครัวขนม', active: true, order: 1, hasProduction: true },
  { id: 'stn-bread', name: 'ครัวผลิตขนมปัง', active: true, order: 2, hasProduction: true },
  { id: 'stn-bar', name: 'ครัวบาร์น้ำ', active: true, order: 3, hasProduction: true },
  { id: 'stn-misc', name: 'ครัวจิปาถะ', active: true, order: 4, hasProduction: false },
];

// ===================== พนักงาน =====================
export const employees: Employee[] = [
  {
    id: 'emp-owner-1',
    name: 'คุณปัง สินสมบูรณ์',
    nickname: 'พี่ปัง',
    role: 'owner',
    avatarColor: '#EA580C',
    pinCode: '1111',
    stationId: null,
      stationIds: [],
    active: true,
    createdAt: '2025-01-05T08:00:00+07:00',
    lastLoginAt: addHours(NOW, -2).toISOString(),
    lastLoginDevice: 'iPhone · Safari',
  },
  {
    id: 'emp-manager-1',
    name: 'สมหญิง ดูแลดี',
    nickname: 'พี่หญิง',
    role: 'manager',
    avatarColor: '#0EA5E9',
    pinCode: '2222',
    stationId: null,
      stationIds: [],
    active: true,
    createdAt: '2025-01-10T08:00:00+07:00',
    lastLoginAt: addHours(NOW, -5).toISOString(),
    lastLoginDevice: 'Android · Chrome',
  },
  {
    id: 'emp-staff-1',
    name: 'มานี ใจดี',
    nickname: 'มานี',
    role: 'staff',
    avatarColor: '#16A34A',
    pinCode: '3333',
    stationId: 'stn-bar',
      stationIds: ['stn-bar'],
    active: true,
    createdAt: '2025-02-01T08:00:00+07:00',
    lastLoginAt: addHours(NOW, -20).toISOString(),
    lastLoginDevice: 'Android · Chrome',
  },
  {
    id: 'emp-staff-2',
    name: 'สมชาย ขยันมาก',
    nickname: 'ชาย',
    role: 'staff',
    avatarColor: '#9333EA',
    pinCode: '4444',
    stationId: 'stn-dessert',
      stationIds: ['stn-dessert'],
    active: true,
    createdAt: '2025-02-15T08:00:00+07:00',
    lastLoginAt: null,
    lastLoginDevice: null,
  },
  {
    id: 'emp-staff-3',
    name: 'วิภา ตั้งใจทำ',
    nickname: 'วิ',
    role: 'staff',
    avatarColor: '#DB2777',
    pinCode: '5555',
    stationId: 'stn-bread',
      stationIds: ['stn-bread'],
    active: true,
    createdAt: '2025-03-01T08:00:00+07:00',
    lastLoginAt: addHours(NOW, -30).toISOString(),
    lastLoginDevice: 'iPad · Safari',
  },
];

// ===================== วันหยุดร้าน (ข้ามการแจ้งเตือนเช็กลิสต์/สรุปปิดร้านในวันนี้) =====================
export const storeHolidays: StoreHoliday[] = [
  {
    id: 'holiday-001',
    date: toDateStr(addDays(NOW, 14)),
    label: 'วันหยุดประจำปี',
    createdBy: 'emp-owner-1',
    createdAt: addDays(NOW, -10).toISOString(),
  },
];

// ===================== หมวดหมู่สต๊อก =====================
export const stockCategories: StockCategory[] = [
  { id: 'cat-bakery', name: 'ขนมปัง' },
  { id: 'cat-sauce', name: 'ของสด' },
  { id: 'cat-frozen', name: 'ของแช่แข็ง' },
  { id: 'cat-packaging', name: 'บรรจุภัณฑ์' },
  { id: 'cat-syrup', name: 'ไซรัป' },
  { id: 'cat-flour', name: 'แป้ง' },
  { id: 'cat-milk', name: 'นม' },
  { id: 'cat-other', name: 'จิปาถะ' },
];

// ===================== วัตถุดิบ/สต๊อก =====================
export const stockItems: StockItem[] = [
  {
    id: 'stk-001',
    name: 'นมสด UHT',
    categoryId: 'cat-milk',
    quantity: 18,
    unit: 'ลิตร',
    minQuantity: 10,
    parQuantity: 30,
    expiryDate: toDateStr(addDays(NOW, 12)),
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -20).toISOString(),
    updatedBy: 'emp-staff-1',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-002',
    name: 'นมโอ๊ต',
    categoryId: 'cat-milk',
    quantity: 4,
    unit: 'ลิตร',
    minQuantity: 6,
    parQuantity: 15,
    expiryDate: toDateStr(addDays(NOW, 20)),
    status: 'low',
    note: 'เหลือน้อยกว่ากำหนด',
    updatedAt: addHours(NOW, -5).toISOString(),
    updatedBy: 'emp-staff-2',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-003',
    name: 'โยเกิร์ต',
    categoryId: 'cat-milk',
    quantity: 6,
    unit: 'ถ้วย',
    minQuantity: 5,
    parQuantity: 12,
    expiryDate: toDateStr(addDays(NOW, 2)),
    status: 'near_expiry',
    note: 'ใกล้หมดอายุ ใช้ก่อน',
    updatedAt: addHours(NOW, -18).toISOString(),
    updatedBy: 'emp-staff-1',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-004',
    name: 'สตรอว์เบอร์รีแยม',
    categoryId: 'cat-other',
    quantity: 2,
    unit: 'ขวด',
    minQuantity: 2,
    parQuantity: 6,
    expiryDate: toDateStr(addDays(NOW, 45)),
    status: 'low',
    note: '',
    updatedAt: addHours(NOW, -30).toISOString(),
    updatedBy: 'emp-staff-3',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-005',
    name: 'ซอสช็อกโกแลต',
    categoryId: 'cat-other',
    quantity: 5,
    unit: 'ขวด',
    minQuantity: 3,
    parQuantity: 8,
    expiryDate: toDateStr(addDays(NOW, 60)),
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -30).toISOString(),
    updatedBy: 'emp-staff-3',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-006',
    name: 'ซอสคาราเมล',
    categoryId: 'cat-other',
    quantity: 0,
    unit: 'ขวด',
    minQuantity: 2,
    parQuantity: 6,
    expiryDate: null,
    status: 'out',
    note: 'หมดตั้งแต่เมื่อวาน',
    updatedAt: addHours(NOW, -14).toISOString(),
    updatedBy: 'emp-staff-2',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-007',
    name: 'ผงชาไทย',
    categoryId: 'cat-syrup',
    quantity: 3,
    unit: 'กก.',
    minQuantity: 2,
    parQuantity: 5,
    expiryDate: toDateStr(addDays(NOW, 120)),
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -48).toISOString(),
    updatedBy: 'emp-staff-1',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-008',
    name: 'ผงมัทฉะ',
    categoryId: 'cat-syrup',
    quantity: 1.5,
    unit: 'กก.',
    minQuantity: 1,
    parQuantity: 4,
    expiryDate: toDateStr(addDays(NOW, 90)),
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -48).toISOString(),
    updatedBy: 'emp-staff-1',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-009',
    name: 'น้ำเชื่อม',
    categoryId: 'cat-syrup',
    quantity: 8,
    unit: 'ขวด',
    minQuantity: 4,
    parQuantity: 10,
    expiryDate: toDateStr(addDays(NOW, 200)),
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -48).toISOString(),
    updatedBy: 'emp-staff-2',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-010',
    name: 'วิปปิ้งครีม',
    categoryId: 'cat-milk',
    quantity: 3,
    unit: 'กล่อง',
    minQuantity: 3,
    parQuantity: 8,
    expiryDate: toDateStr(addDays(NOW, 25)),
    status: 'low',
    note: '',
    updatedAt: addHours(NOW, -10).toISOString(),
    updatedBy: 'emp-staff-3',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-011',
    name: 'ขนมปังแซนด์วิช',
    categoryId: 'cat-bakery',
    quantity: 12,
    unit: 'แถว',
    minQuantity: 8,
    parQuantity: 20,
    expiryDate: toDateStr(addDays(NOW, 3)),
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -6).toISOString(),
    updatedBy: 'emp-staff-2',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-012',
    name: 'เนย',
    categoryId: 'cat-bakery',
    quantity: 2,
    unit: 'กก.',
    minQuantity: 1,
    parQuantity: 3,
    expiryDate: toDateStr(addDays(NOW, 40)),
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -48).toISOString(),
    updatedBy: 'emp-staff-1',
    active: true,
    supplierId: 'sup-001',
  },
  {
    id: 'stk-013',
    name: 'น้ำแข็ง',
    categoryId: 'cat-other',
    quantity: 15,
    unit: 'ถุง',
    minQuantity: 10,
    parQuantity: 25,
    expiryDate: null,
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -3).toISOString(),
    updatedBy: 'emp-staff-3',
    active: true,
    // ยังไม่ระบุผู้ขาย — ตัวอย่างรายการที่เจ้าของยังไม่ได้กำหนดผู้ขาย จะไม่แสดงในหน้า "สั่งสินค้า" จนกว่าจะตั้งค่า
    supplierId: null,
  },
  {
    id: 'stk-014',
    name: 'แก้วพลาสติก 16 oz',
    categoryId: 'cat-packaging',
    quantity: 120,
    unit: 'ใบ',
    minQuantity: 100,
    parQuantity: 500,
    expiryDate: null,
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -72).toISOString(),
    updatedBy: 'emp-manager-1',
    active: true,
    supplierId: 'sup-002',
  },
  {
    id: 'stk-015',
    name: 'ฝาแก้ว',
    categoryId: 'cat-packaging',
    quantity: 80,
    unit: 'ใบ',
    minQuantity: 100,
    parQuantity: 500,
    expiryDate: null,
    status: 'low',
    note: '',
    updatedAt: addHours(NOW, -72).toISOString(),
    updatedBy: 'emp-manager-1',
    active: true,
    supplierId: 'sup-002',
  },
  {
    id: 'stk-016',
    name: 'หลอด',
    categoryId: 'cat-packaging',
    quantity: 300,
    unit: 'ชิ้น',
    minQuantity: 150,
    parQuantity: 600,
    expiryDate: null,
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -72).toISOString(),
    updatedBy: 'emp-manager-1',
    active: true,
    supplierId: 'sup-002',
  },
  {
    id: 'stk-017',
    name: 'ถุงหิ้ว',
    categoryId: 'cat-packaging',
    quantity: 40,
    unit: 'ใบ',
    minQuantity: 50,
    parQuantity: 200,
    expiryDate: null,
    status: 'low',
    note: '',
    updatedAt: addHours(NOW, -72).toISOString(),
    updatedBy: 'emp-manager-1',
    active: true,
    supplierId: 'sup-002',
  },
  {
    id: 'stk-018',
    name: 'กล่องบรรจุภัณฑ์',
    categoryId: 'cat-packaging',
    quantity: 60,
    unit: 'ใบ',
    minQuantity: 30,
    parQuantity: 150,
    expiryDate: null,
    status: 'normal',
    note: '',
    updatedAt: addHours(NOW, -72).toISOString(),
    updatedBy: 'emp-manager-1',
    active: true,
    supplierId: 'sup-002',
  },
];

// ===================== เช็กลิสต์: template แยกตามแผนก (แต่ละแผนกรายการไม่เหมือนกัน) =====================
export const checklistTemplate: ChecklistTemplateItem[] = [
  // ครัวขนม
  { id: 'tpl-dessert-01', stationId: 'stn-dessert', label: 'ชิมครีมสด', order: 1, active: true },
  { id: 'tpl-dessert-02', stationId: 'stn-dessert', label: 'ชิมซอสสตรอว์เบอร์รี', order: 2, active: true },
  { id: 'tpl-dessert-03', stationId: 'stn-dessert', label: 'ตรวจสี กลิ่น และรสชาติวัตถุดิบ', order: 3, active: true },
  { id: 'tpl-dessert-04', stationId: 'stn-dessert', label: 'ตรวจวันผลิต/วันหมดอายุ', order: 4, active: true },
  { id: 'tpl-dessert-05', stationId: 'stn-dessert', label: 'ตรวจอุณหภูมิตู้เย็น', order: 5, active: true },
  { id: 'tpl-dessert-06', stationId: 'stn-dessert', label: 'ตรวจความสะอาดบริเวณครัว', order: 6, active: true },
  { id: 'tpl-dessert-07', stationId: 'stn-dessert', label: 'ตรวจวัตถุดิบที่ใกล้หมด', order: 7, active: true },

  // ครัวผลิตขนมปัง
  { id: 'tpl-bread-01', stationId: 'stn-bread', label: 'ชิมเนย', order: 1, active: true },
  { id: 'tpl-bread-02', stationId: 'stn-bread', label: 'ตรวจแป้ง/ยีสต์', order: 2, active: true },
  { id: 'tpl-bread-03', stationId: 'stn-bread', label: 'ตรวจอุปกรณ์อบขนมปัง', order: 3, active: true },
  { id: 'tpl-bread-04', stationId: 'stn-bread', label: 'ตรวจวันผลิต/วันหมดอายุ', order: 4, active: true },
  { id: 'tpl-bread-05', stationId: 'stn-bread', label: 'ตรวจความสะอาดบริเวณครัว', order: 5, active: true },
  { id: 'tpl-bread-06', stationId: 'stn-bread', label: 'ตรวจวัตถุดิบที่ใกล้หมด', order: 6, active: true },

  // ครัวบาร์น้ำ
  { id: 'tpl-bar-01', stationId: 'stn-bar', label: 'ชิมนม', order: 1, active: true },
  { id: 'tpl-bar-02', stationId: 'stn-bar', label: 'ชิมโยเกิร์ต', order: 2, active: true },
  { id: 'tpl-bar-03', stationId: 'stn-bar', label: 'ตรวจอุปกรณ์ต้มนม/ชงเครื่องดื่ม', order: 3, active: true },
  { id: 'tpl-bar-04', stationId: 'stn-bar', label: 'ตรวจวันผลิต/วันหมดอายุ', order: 4, active: true },
  { id: 'tpl-bar-05', stationId: 'stn-bar', label: 'ตรวจอุณหภูมิตู้เย็น', order: 5, active: true },
  { id: 'tpl-bar-06', stationId: 'stn-bar', label: 'ตรวจความสะอาดบริเวณบาร์', order: 6, active: true },
  { id: 'tpl-bar-07', stationId: 'stn-bar', label: 'ตรวจบรรจุภัณฑ์ (แก้ว ฝา หลอด)', order: 7, active: true },

  // ครัวจิปาถะ (ไม่มีระบบผลิต — เช็กเฉพาะสต๊อก/ความสะอาด)
  { id: 'tpl-misc-01', stationId: 'stn-misc', label: 'ตรวจความสะอาดพื้นที่จัดเก็บ', order: 1, active: true },
  { id: 'tpl-misc-02', stationId: 'stn-misc', label: 'ตรวจบรรจุภัณฑ์คงเหลือ', order: 2, active: true },
  { id: 'tpl-misc-03', stationId: 'stn-misc', label: 'ตรวจวัตถุดิบที่ใกล้หมด', order: 3, active: true },
];

// ===================== เช็กลิสต์: เมื่อวาน (ทำครบทุกแผนก) + วันนี้ (บางแผนกทำแล้ว) =====================
function itemsForStation(stationId: string) {
  return checklistTemplate
    .filter((t) => t.stationId === stationId && t.active)
    .map((t) => ({
      templateItemId: t.id,
      label: t.label,
      status: 'normal' as const,
      note: '',
      photoUrl: null,
      quantity: null,
    }));
}

export const checklistRuns: ChecklistRun[] = [
  {
    id: 'chk-dessert-yesterday',
    stationId: 'stn-dessert',
    date: toDateStr(addDays(NOW, -1)),
    submittedAt: addHours(addDays(NOW, -1), 9).toISOString(),
    submittedBy: 'emp-staff-2',
    items: itemsForStation('stn-dessert'),
    isComplete: true,
    backdated: false,
    backdatedReason: null,
  },
  {
    id: 'chk-bread-yesterday',
    stationId: 'stn-bread',
    date: toDateStr(addDays(NOW, -1)),
    submittedAt: addHours(addDays(NOW, -1), 9.5).toISOString(),
    submittedBy: 'emp-staff-3',
    items: itemsForStation('stn-bread'),
    isComplete: true,
    backdated: false,
    backdatedReason: null,
  },
  {
    id: 'chk-bar-yesterday',
    stationId: 'stn-bar',
    date: toDateStr(addDays(NOW, -1)),
    submittedAt: addHours(addDays(NOW, -1), 9.2).toISOString(),
    submittedBy: 'emp-staff-1',
    items: itemsForStation('stn-bar'),
    isComplete: true,
    backdated: false,
    backdatedReason: null,
  },
  {
    id: 'chk-misc-yesterday',
    stationId: 'stn-misc',
    date: toDateStr(addDays(NOW, -1)),
    submittedAt: addHours(addDays(NOW, -1), 9.8).toISOString(),
    submittedBy: 'emp-manager-1',
    items: itemsForStation('stn-misc'),
    isComplete: true,
    backdated: false,
    backdatedReason: null,
  },
  {
    id: 'chk-bar-today',
    stationId: 'stn-bar',
    date: TODAY_STR,
    submittedAt: addHours(NOW, -2).toISOString(),
    submittedBy: 'emp-staff-1',
    items: itemsForStation('stn-bar'),
    isComplete: true,
    backdated: false,
    backdatedReason: null,
  },
  {
    id: 'chk-dessert-today',
    stationId: 'stn-dessert',
    date: TODAY_STR,
    submittedAt: null,
    submittedBy: null,
    items: [],
    isComplete: false,
    backdated: false,
    backdatedReason: null,
  },
  {
    id: 'chk-bread-today',
    stationId: 'stn-bread',
    date: TODAY_STR,
    submittedAt: null,
    submittedBy: null,
    items: [],
    isComplete: false,
    backdated: false,
    backdatedReason: null,
  },
  {
    id: 'chk-misc-today',
    stationId: 'stn-misc',
    date: TODAY_STR,
    submittedAt: null,
    submittedBy: null,
    items: [],
    isComplete: false,
    backdated: false,
    backdatedReason: null,
  },
];

// ===================== สินค้าที่แผนกผลิต (เฉพาะแผนกที่ hasProduction = true) =====================
export const products: Product[] = [
  { id: 'prod-milk', stationId: 'stn-bar', name: 'นมต้ม', unit: 'ลิตร', shelfLifeDays: 3, active: true },
  { id: 'prod-bread-butter', stationId: 'stn-bread', name: 'ขนมปังเนย', unit: 'ชิ้น', shelfLifeDays: 2, active: true },
  { id: 'prod-strawberry-sauce', stationId: 'stn-dessert', name: 'ซอสสตรอว์เบอร์รี', unit: 'ถ้วย', shelfLifeDays: 4, active: true },
];

// ===================== ล็อตการผลิต (แทน milkBatches เดิม — ใช้ได้ทุกแผนกที่มีการผลิต) =====================
export const productLots: ProductLot[] = [
  {
    id: 'lot-001',
    productId: 'prod-milk',
    lotNumber: 'M-0231',
    producedDate: toDateStr(addDays(NOW, -2)),
    producedTime: '07:30',
    quantity: 20,
    unit: 'ลิตร',
    producedBy: 'emp-staff-1',
    shelfLifeDays: 3,
    expiresAt: addHours(addDays(NOW, -2), 24 * 3 + 7.5).toISOString(),
    note: '',
    photoUrl: null,
    status: 'used_up',
    usedUpAt: addHours(addDays(NOW, -1), 20).toISOString(),
    createdAt: addHours(addDays(NOW, -2), 7.5).toISOString(),
  },
  {
    id: 'lot-002',
    productId: 'prod-milk',
    lotNumber: 'M-0232',
    producedDate: toDateStr(addDays(NOW, -1)),
    producedTime: '07:15',
    quantity: 18,
    unit: 'ลิตร',
    producedBy: 'emp-staff-1',
    shelfLifeDays: 3,
    expiresAt: addDays(NOW, 1).toISOString(),
    note: 'ต้มเผื่อวันหยุดยาว',
    photoUrl: null,
    status: 'near_expiry',
    usedUpAt: null,
    createdAt: addHours(addDays(NOW, -1), 7.25).toISOString(),
  },
  {
    id: 'lot-003',
    productId: 'prod-bread-butter',
    lotNumber: 'B-0044',
    producedDate: toDateStr(addDays(NOW, -3)),
    producedTime: '05:30',
    quantity: 40,
    unit: 'ชิ้น',
    producedBy: 'emp-staff-3',
    shelfLifeDays: 2,
    expiresAt: addDays(NOW, -1).toISOString(),
    note: '',
    photoUrl: null,
    status: 'expired',
    usedUpAt: null,
    createdAt: addHours(addDays(NOW, -3), 5.5).toISOString(),
  },
  {
    id: 'lot-004',
    productId: 'prod-strawberry-sauce',
    lotNumber: 'S-0012',
    producedDate: TODAY_STR,
    producedTime: '06:45',
    quantity: 8,
    unit: 'ถ้วย',
    producedBy: 'emp-staff-2',
    shelfLifeDays: 4,
    expiresAt: addDays(NOW, 4).toISOString(),
    note: '',
    photoUrl: null,
    status: 'active',
    usedUpAt: null,
    createdAt: addHours(NOW, -1).toISOString(),
  },
];

// ===================== รายการเสนอซื้อ =====================
export const purchaseRequests: PurchaseRequest[] = [
  {
    id: 'pr-001',
    stockItemId: 'stk-006',
    itemName: 'ซอสคาราเมล',
    currentQuantity: 0,
    requestedQuantity: 6,
    unit: 'ขวด',
    reason: 'สต๊อกหมด ลูกค้าสั่งเมนูที่ต้องใช้บ่อย',
    neededBy: toDateStr(addDays(NOW, 1)),
    requestedBy: 'emp-staff-2',
    photoUrl: null,
    status: 'pending',
    approvedBy: null,
    approvedAt: null,
    receivedAt: null,
    autoGenerated: true,
    createdAt: addHours(NOW, -14).toISOString(),
  },
  {
    id: 'pr-002',
    stockItemId: 'stk-017',
    itemName: 'ถุงหิ้ว',
    currentQuantity: 40,
    requestedQuantity: 300,
    unit: 'ใบ',
    reason: 'ต่ำกว่าจำนวนขั้นต่ำที่ตั้งไว้',
    neededBy: toDateStr(addDays(NOW, 3)),
    requestedBy: 'emp-manager-1',
    photoUrl: null,
    status: 'ordered',
    approvedBy: 'emp-owner-1',
    approvedAt: addHours(NOW, -20).toISOString(),
    receivedAt: null,
    autoGenerated: true,
    createdAt: addHours(NOW, -22).toISOString(),
  },
  {
    id: 'pr-003',
    stockItemId: 'stk-015',
    itemName: 'ฝาแก้ว',
    currentQuantity: 80,
    requestedQuantity: 500,
    unit: 'ใบ',
    reason: 'ใกล้ต่ำกว่าขั้นต่ำ เผื่อสั่งพร้อมแก้ว',
    neededBy: toDateStr(addDays(NOW, 5)),
    requestedBy: 'emp-staff-3',
    photoUrl: null,
    status: 'ordered',
    approvedBy: 'emp-manager-1',
    approvedAt: addHours(NOW, -40).toISOString(),
    receivedAt: null,
    autoGenerated: true,
    createdAt: addHours(NOW, -44).toISOString(),
  },
  {
    id: 'pr-004',
    stockItemId: null,
    itemName: 'ผงมัทฉะเกรดพรีเมียม (ทดลองสูตรใหม่)',
    currentQuantity: 0,
    requestedQuantity: 2,
    unit: 'กก.',
    reason: 'เจ้าของร้านอยากทดลองสูตรเมนูใหม่',
    neededBy: toDateStr(addDays(NOW, 7)),
    requestedBy: 'emp-owner-1',
    photoUrl: null,
    status: 'received',
    approvedBy: 'emp-owner-1',
    approvedAt: addHours(NOW, -100).toISOString(),
    receivedAt: addHours(NOW, -50).toISOString(),
    autoGenerated: false,
    createdAt: addHours(NOW, -120).toISOString(),
  },
];

// ===================== ผู้ขาย/ซัพพลายเออร์ =====================
export const suppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: 'ร้านวัตถุดิบเบเกอรี่ไทย',
    contactPerson: 'คุณโกวิท',
    phone: '081-234-5678',
    address: '12 ถ.เจริญกรุง กรุงเทพฯ',
    note: 'ส่งของทุกวันจันทร์/พฤหัส',
    active: true,
  },
  {
    id: 'sup-002',
    name: 'บริษัท แพคเกจจิ้งพลัส จำกัด',
    contactPerson: 'คุณสุนีย์',
    phone: '089-876-5432',
    address: '99 นิคมอุตสาหกรรมบางพลี สมุทรปราการ',
    note: 'สั่งขั้นต่ำ 2,000 บาท ฟรีค่าส่ง',
    active: true,
  },
];

// ===================== ประวัติราคา (append-only — เพิ่มแถวใหม่เสมอเมื่อราคาเปลี่ยน) =====================
export const supplierItemPrices: SupplierItemPrice[] = [
  {
    id: 'price-001',
    supplierId: 'sup-001',
    stockItemId: 'stk-004',
    unit: 'ขวด',
    price: 85,
    note: '',
    createdBy: 'emp-manager-1',
    createdAt: addDays(NOW, -60).toISOString(),
  },
  {
    id: 'price-002',
    supplierId: 'sup-002',
    stockItemId: 'stk-017',
    unit: 'ใบ',
    price: 1.2,
    note: 'ราคาเริ่มต้น',
    createdBy: 'emp-manager-1',
    createdAt: addDays(NOW, -90).toISOString(),
  },
  {
    id: 'price-003',
    supplierId: 'sup-002',
    stockItemId: 'stk-017',
    unit: 'ใบ',
    price: 1.35,
    note: 'ราคาปรับขึ้นจากผู้ขาย',
    createdBy: 'emp-owner-1',
    createdAt: addDays(NOW, -10).toISOString(),
  },
  {
    id: 'price-004',
    supplierId: 'sup-002',
    stockItemId: 'stk-015',
    unit: 'ใบ',
    price: 2.1,
    note: '',
    createdBy: 'emp-manager-1',
    createdAt: addDays(NOW, -30).toISOString(),
  },
];

// ===================== ใบสั่งซื้อ (สร้าง/รวมจากรายการเสนอซื้อที่อนุมัติแล้ว) =====================
export const purchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-001',
    supplierId: 'sup-002',
    orderDate: toDateStr(addDays(NOW, -1)),
    status: 'sent',
    note: '',
    createdBy: 'emp-manager-1',
    createdAt: addHours(NOW, -19).toISOString(),
    sentAt: addHours(NOW, -19).toISOString(),
    receivedAt: null,
    receivedBy: null,
    items: [
      {
        id: 'poi-001',
        purchaseOrderId: 'po-001',
        stockItemId: 'stk-017',
        itemName: 'ถุงหิ้ว',
        quantity: 300,
        unit: 'ใบ',
        unitPrice: 1.35,
        sourcePurchaseRequestId: 'pr-002',
      },
      {
        id: 'poi-002',
        purchaseOrderId: 'po-001',
        stockItemId: 'stk-015',
        itemName: 'ฝาแก้ว',
        quantity: 500,
        unit: 'ใบ',
        unitPrice: 2.1,
        sourcePurchaseRequestId: 'pr-003',
      },
    ],
  },
];

// ===================== รายงานเงินสดปิดร้าน (แบบง่าย) =====================
export const cashReports: CashReport[] = [
  {
    id: 'cash-001',
    date: toDateStr(addDays(NOW, -1)),
    closingAmount: 8450,
    note: 'ปกติดี ไม่มีส่วนต่าง',
    submittedBy: 'emp-manager-1',
    submittedAt: addHours(addDays(NOW, -1), 12).toISOString(),
  },
];

// ===================== แจ้งเตือนให้แผนกสั่งสินค้า (เฟส 5) — ค่าเริ่มต้นว่างเปล่า =====================
export const orderReminders: OrderReminder[] = [];

// ===================== การแจ้งเตือน =====================
export const notifications: AppNotification[] = [
  {
    id: 'noti-001',
    type: 'checklist_missing',
    severity: 'urgent',
    title: 'ยังไม่ได้ทำเช็กลิสต์วันนี้',
    message: 'ยังไม่มีพนักงานทำเช็กลิสต์แผนกครัวขนมประจำวันของวันนี้',
    relatedId: 'stn-dessert',
    createdAt: addHours(NOW, -1).toISOString(),
    readBy: [],
  },
  {
    id: 'noti-002',
    type: 'lot_expired',
    severity: 'blocked',
    title: 'ขนมปังเนยหมดอายุ — ห้ามใช้',
    message: 'ล็อต B-0044 หมดอายุแล้ว ห้ามนำไปใช้ กรุณาทิ้งและบันทึกสถานะ',
    relatedId: 'lot-003',
    createdAt: addHours(NOW, -6).toISOString(),
    readBy: [],
  },
  {
    id: 'noti-003',
    type: 'lot_near_expiry',
    severity: 'review',
    title: 'นมต้มใกล้หมดอายุ',
    message: 'ล็อต M-0232 จะหมดอายุภายใน 1 วัน ควรใช้ให้หมดก่อน',
    relatedId: 'lot-002',
    createdAt: addHours(NOW, -3).toISOString(),
    readBy: ['emp-manager-1'],
  },
  {
    id: 'noti-004',
    type: 'stock_out',
    severity: 'urgent',
    title: 'สินค้าหมด: ซอสคาราเมล',
    message: 'ซอสคาราเมลหมดสต๊อกแล้ว ระบบสร้างรายการเสนอซื้อให้อัตโนมัติ',
    relatedId: 'stk-006',
    createdAt: addHours(NOW, -14).toISOString(),
    readBy: [],
  },
  {
    id: 'noti-005',
    type: 'stock_low',
    severity: 'review',
    title: 'วัตถุดิบใกล้หมด: นมโอ๊ต',
    message: 'นมโอ๊ตเหลือ 4 ลิตร ต่ำกว่าจำนวนขั้นต่ำ (6 ลิตร)',
    relatedId: 'stk-002',
    createdAt: addHours(NOW, -5).toISOString(),
    readBy: [],
  },
  {
    id: 'noti-006',
    type: 'purchase_pending',
    severity: 'review',
    title: 'มีรายการเสนอซื้อรออนุมัติ',
    message: 'ซอสคาราเมล 6 ขวด รอการอนุมัติจากผู้จัดการหรือเจ้าของร้าน',
    relatedId: 'pr-001',
    createdAt: addHours(NOW, -14).toISOString(),
    readBy: [],
  },
  {
    id: 'noti-007',
    type: 'purchase_not_received',
    severity: 'info',
    title: 'สินค้าที่สั่งยังไม่ได้รับ',
    message: 'ฝาแก้ว 500 ใบ สั่งซื้อแล้วแต่ยังไม่ได้รับสินค้า',
    relatedId: 'pr-003',
    createdAt: addHours(NOW, -40).toISOString(),
    readBy: [],
  },
];

// ===================== ประวัติการใช้งาน =====================
export const historyLogs: HistoryLog[] = [
  {
    id: 'log-001',
    actionType: 'checklist_submit',
    actorId: 'emp-staff-2',
    targetLabel: `ครัวขนม · เช็กลิสต์วันที่ ${toDateStr(addDays(NOW, -1))}`,
    detail: 'ทำเช็กลิสต์ครบทุกข้อ ทุกรายการปกติ',
    createdAt: addHours(addDays(NOW, -1), 9).toISOString(),
  },
  {
    id: 'log-001b',
    actionType: 'checklist_submit',
    actorId: 'emp-staff-1',
    targetLabel: `ครัวบาร์น้ำ · เช็กลิสต์วันที่ ${TODAY_STR}`,
    detail: 'ทำเช็กลิสต์ครบทุกข้อ ทุกรายการปกติ',
    createdAt: addHours(NOW, -2).toISOString(),
  },
  {
    id: 'log-002',
    actionType: 'production_log',
    actorId: 'emp-staff-2',
    targetLabel: 'ซอสสตรอว์เบอร์รี ล็อต S-0012',
    detail: 'ผลิตซอสสตรอว์เบอร์รี 8 ถ้วย อายุการเก็บ 4 วัน',
    createdAt: addHours(NOW, -1).toISOString(),
  },
  {
    id: 'log-003',
    actionType: 'lot_status_change',
    actorId: 'emp-staff-1',
    targetLabel: 'นมต้ม ล็อต M-0231',
    detail: 'เปลี่ยนสถานะเป็น "ใช้หมดแล้ว"',
    createdAt: addHours(addDays(NOW, -1), 20).toISOString(),
  },
  {
    id: 'log-004',
    actionType: 'stock_adjust',
    actorId: 'emp-staff-2',
    targetLabel: 'ซอสคาราเมล',
    detail: 'ปรับจำนวนคงเหลือเป็น 0 (หมด)',
    createdAt: addHours(NOW, -14).toISOString(),
  },
  {
    id: 'log-005',
    actionType: 'purchase_create',
    actorId: 'emp-staff-2',
    targetLabel: 'ซอสคาราเมล',
    detail: 'สร้างรายการเสนอซื้ออัตโนมัติจากสต๊อกหมด',
    createdAt: addHours(NOW, -14).toISOString(),
  },
  {
    id: 'log-006',
    actionType: 'purchase_approve',
    actorId: 'emp-owner-1',
    targetLabel: 'ถุงหิ้ว',
    detail: 'อนุมัติรายการเสนอซื้อ 300 ใบ',
    createdAt: addHours(NOW, -20).toISOString(),
  },
  {
    id: 'log-007',
    actionType: 'purchase_receive',
    actorId: 'emp-manager-1',
    targetLabel: 'ผงมัทฉะเกรดพรีเมียม',
    detail: 'รับสินค้าเข้าสต๊อกเรียบร้อย 2 กก.',
    createdAt: addHours(NOW, -50).toISOString(),
  },
  {
    id: 'log-008',
    actionType: 'settings_change',
    actorId: 'emp-owner-1',
    targetLabel: 'ตั้งค่าระบบ',
    detail: 'เปลี่ยนเวลาสุดท้ายที่ต้องทำเช็กลิสต์เป็น 10:00 น.',
    createdAt: addHours(NOW, -240).toISOString(),
  },
];

// ===================== การตั้งค่า =====================
export const appSettings: AppSettings = {
  checklistStartTime: '07:00',
  checklistDueTime: '10:00',
  milkShelfLifeDays: 3,
  notifyLeadHoursBeforeExpiry: 4,
  lowStockNotifyEnabled: true,
  closingTime: '20:00',
  closingSummaryEnabled: true,
};
